import React, { useState, useEffect } from "react";
import { ArrowLeft, Clock, Bell, Rocket, Timer, Play, Pause, AlertOctagon, Check, Plus, Landmark, Brain, ShieldAlert, Sparkles, TrendingUp, Compass } from "lucide-react";
import { RescuePlan, Milestone, ViewType } from "../types";

interface ExecutionViewProps {
  plan: RescuePlan;
  setView: (view: ViewType) => void;
  onUpdateMilestones: (updated: Milestone[]) => void;
}

export default function ExecutionView({ plan, setView, onUpdateMilestones }: ExecutionViewProps) {
  // Active step index (default to the first "WORKING NOW" step, or first step)
  const activeStepIndex = plan.milestones.findIndex(m => m.status === "WORKING NOW");
  const [activeStep, setActiveStep] = useState(activeStepIndex !== -1 ? activeStepIndex : 0);

  // Active timer states
  const [isTimerRunning, setIsTimerRunning] = useState(false);
  const [seconds, setSeconds] = useState(1452); // Starting at 24 mins 12 secs (24*60 + 12 = 1452)

  // Live ticking general clock
  const [currentTime, setCurrentTime] = useState("");

  // Add Milestone Form state
  const [showAddForm, setShowAddForm] = useState(false);
  const [newTitle, setNewTitle] = useState("");
  const [newDesc, setNewDesc] = useState("");
  const [newDiff, setNewDiff] = useState("Medium");

  // Emergency Modal state
  const [showEmergencyModal, setShowEmergencyModal] = useState(false);

  // Update current clock time
  useEffect(() => {
    const updateTime = () => {
      const now = new Date();
      setCurrentTime(now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }));
    };
    updateTime();
    const interval = setInterval(updateTime, 1000);
    return () => clearInterval(interval);
  }, []);

  // Update Session Timer
  useEffect(() => {
    let interval: any = null;
    if (isTimerRunning) {
      interval = setInterval(() => {
        setSeconds(prev => prev + 1);
      }, 1000);
    } else {
      clearInterval(interval);
    }
    return () => clearInterval(interval);
  }, [isTimerRunning]);

  // Format session time
  const formatSessionTime = (totalSecs: number) => {
    const mins = Math.floor(totalSecs / 60);
    const secs = totalSecs % 60;
    return `${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  };

  // Toggle timer
  const handleToggleTimer = () => {
    setIsTimerRunning(!isTimerRunning);
  };

  // Skip or advance step
  const handleNextStep = () => {
    const nextIndex = activeStep + 1;
    if (nextIndex < plan.milestones.length) {
      // Transition statuses
      const updated = [...plan.milestones];
      // Set current to completed
      updated[activeStep] = {
        ...updated[activeStep],
        status: "COMPLETED",
        durationTracked: `${(seconds / 3600).toFixed(1)}h tracked`
      };
      // Set next to working
      updated[nextIndex] = {
        ...updated[nextIndex],
        status: "WORKING NOW"
      };
      onUpdateMilestones(updated);
      setActiveStep(nextIndex);
      setSeconds(0); // Reset timer for new step
    } else {
      // Finished all steps!
      const updated = [...plan.milestones];
      updated[activeStep] = {
        ...updated[activeStep],
        status: "COMPLETED",
        durationTracked: "1.0h tracked"
      };
      onUpdateMilestones(updated);
      alert("Congratulations! You've successfully completed your executive priority roadmap!");
      setView("dashboard");
    }
  };

  // Add custom milestone
  const handleAddMilestone = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle.trim()) return;

    const newMilestone: Milestone = {
      title: newTitle.trim(),
      description: newDesc.trim() || "Dynamic milestone generated by user.",
      durationTracked: "Not started",
      status: "UPCOMING",
      difficulty: newDiff
    };

    const updated = [...plan.milestones, newMilestone];
    onUpdateMilestones(updated);
    
    // Reset Form
    setNewTitle("");
    setNewDesc("");
    setShowAddForm(false);
  };

  // Select any step on the roadmap
  const handleSelectStep = (index: number) => {
    const updated = [...plan.milestones];
    // Clear old working status
    updated.forEach((m, idx) => {
      if (m.status === "WORKING NOW") {
        updated[idx] = { ...m, status: idx < index ? "COMPLETED" : "UPCOMING" };
      }
    });
    // Set new working status
    updated[index] = { ...updated[index], status: "WORKING NOW" };
    onUpdateMilestones(updated);
    setActiveStep(index);
    setSeconds(0);
  };

  const currentStepData = plan.milestones[activeStep] || plan.milestones[0];

  return (
    <main className="flex-1 min-h-screen pb-16 font-sans bg-[#0A0A0A]">
      {/* Top Header Bar */}
      <header className="w-full h-20 bg-[#0A0A0A] border-b border-white/10 flex items-center sticky top-0 z-30">
        <div className="flex justify-between items-center w-full px-6 max-w-7xl mx-auto">
          <div className="flex items-center gap-4">
            <button
              onClick={() => setView("dashboard")}
              className="p-2 hover:bg-white/5 border border-transparent hover:border-white/10 text-white/60 hover:text-white cursor-pointer"
            >
              <ArrowLeft size={18} />
            </button>
            <div className="flex flex-col">
              <h2 className="text-xl md:text-2xl font-black font-display italic text-white leading-tight">
                {plan.focusTask.title}
              </h2>
              <div className="flex items-center gap-2 mt-1">
                <span className="text-[10px] font-mono font-bold text-primary bg-primary/10 border border-primary/20 px-2.5 py-0.5">
                  EXECUTION MODE ACTIVE
                </span>
                <span className="w-1 h-1 bg-white/20"></span>
                <span className="text-[10px] font-mono font-bold text-white/40 uppercase tracking-widest">
                  CRITICAL SECTOR
                </span>
              </div>
            </div>
          </div>

          <div className="flex items-center gap-4">
            {/* Live Clock Display */}
            <div className="flex items-center gap-2 px-3.5 py-1.5 bg-[#111111] border border-white/10 text-xs font-mono font-semibold">
              <Clock size={12} className="text-primary" />
              <span className="text-white tracking-widest">{currentTime || "14:22:05"}</span>
            </div>
            <button className="p-2 text-white/40 hover:text-primary transition-all relative hover:bg-white/5">
              <Bell size={18} />
              <span className="absolute top-1.5 right-1.5 w-1.5 h-1.5 bg-primary rounded-full"></span>
            </button>
          </div>
        </div>
      </header>

      {/* Task Content Canvas */}
      <div className="p-6 md:p-10 max-w-7xl mx-auto space-y-10">
        {/* Quick Progress Stats Row */}
        <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          <div className="bg-[#111111] border border-white/10 p-5 flex flex-col gap-1.5">
            <span className="text-[9px] font-mono tracking-widest font-bold text-white/40 uppercase">DEADLINE</span>
            <span className="text-base font-black font-display italic text-red-500">{plan.focusTask.deadline}</span>
          </div>
          <div className="bg-[#111111] border border-white/10 p-5 flex flex-col gap-1.5">
            <span className="text-[9px] font-mono tracking-widest font-bold text-white/40 uppercase">ESTIMATED EFFORT</span>
            <span className="text-base font-black font-display italic text-white">{plan.focusTask.timeEst}</span>
          </div>
          <div className="bg-[#111111] border border-white/10 p-5 flex flex-col gap-1.5">
            <span className="text-[9px] font-mono tracking-widest font-bold text-white/40 uppercase">OVERALL PROGRESS</span>
            <div className="flex items-center gap-3">
              <span className="text-base font-black font-display italic text-primary">{plan.focusTask.overallProgress}%</span>
              <div className="flex-1">
                <div className="w-full bg-[#050505] h-1 overflow-hidden">
                  <div className="bg-primary h-full transition-all duration-700" style={{ width: `${plan.focusTask.overallProgress}%` }}></div>
                </div>
              </div>
            </div>
          </div>
          <div className="bg-[#111111] border border-white/10 p-5 flex flex-col gap-1.5">
            <span className="text-[9px] font-mono tracking-widest font-bold text-white/40 uppercase">STATUS</span>
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 bg-[#CCFF00] animate-pulse"></span>
              <span className="text-xs font-mono font-bold tracking-widest uppercase text-[#CCFF00]">ACTIVE WORKLOOP</span>
            </div>
          </div>
        </section>

        {/* Execution Core */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Focus Steps Column */}
          <section className="lg:col-span-2 space-y-8">
            <div className="bg-[#111111] border border-white/10 p-6 md:p-8 relative overflow-hidden transition-all duration-300">
              <div className="absolute top-0 left-0 w-1.5 h-full bg-primary"></div>
              
              <div className="flex justify-between items-start mb-6">
                <div>
                  <span className="text-[10px] font-mono font-bold text-primary tracking-widest uppercase block mb-2">
                    // CURRENT MILESTONE
                  </span>
                  <h3 className="text-2xl md:text-3xl font-black font-display text-white italic leading-tight">
                    {currentStepData ? currentStepData.title : "No Active Step"}
                  </h3>
                  <p className="text-sm text-white/60 mt-4 max-w-2xl leading-relaxed font-sans font-light">
                    {currentStepData ? currentStepData.description : "Please formulate milestones to start."}
                  </p>
                </div>
                <div className="flex flex-col items-end gap-1 flex-shrink-0">
                  <Rocket className="text-primary opacity-20 animate-pulse" size={28} />
                  <span className="text-[10px] font-mono text-white/40 font-bold uppercase tracking-wider">
                    Step {activeStep + 1} / {plan.milestones.length}
                  </span>
                </div>
              </div>

              {/* Running Trackers */}
              <div className="grid grid-cols-2 gap-6 mb-8">
                <div className="flex items-center gap-3.5 p-4 bg-[#050505] border border-white/5">
                  <Timer className="text-primary flex-shrink-0" size={18} />
                  <div>
                    <p className="text-[9px] font-mono font-bold text-white/40 uppercase tracking-widest">SESSION TRACK</p>
                    <p className="text-lg font-black font-display italic text-white mt-0.5">{formatSessionTime(seconds)}</p>
                  </div>
                </div>
                <div className="flex items-center gap-3.5 p-4 bg-[#050505] border border-white/5">
                  <Brain className="text-primary flex-shrink-0" size={18} />
                  <div>
                    <p className="text-[9px] font-mono font-bold text-white/40 uppercase tracking-widest">COGNITIVE LEVEL</p>
                    <p className="text-lg font-black font-display italic text-white mt-0.5">{currentStepData ? currentStepData.difficulty : "Varying"}</p>
                  </div>
                </div>
              </div>

              {/* Interactive Controllers */}
              <div className="flex flex-wrap items-center gap-4">
                <button
                  onClick={handleToggleTimer}
                  className={`px-6 py-4 font-mono font-bold text-xs uppercase tracking-widest flex items-center justify-center gap-2 transition-all cursor-pointer border active:scale-95 ${
                    isTimerRunning
                      ? "bg-transparent border-white/20 hover:border-white text-white"
                      : "bg-primary border-primary text-black hover:bg-white hover:border-white"
                  }`}
                >
                  {isTimerRunning ? <Pause size={14} fill="currentColor" /> : <Play size={14} fill="currentColor" />}
                  <span>{isTimerRunning ? "Pause Execution Loop" : "Start Execution Loop"}</span>
                </button>

                <button
                  onClick={handleNextStep}
                  className="px-6 py-4 border border-white/10 text-white/60 hover:text-white hover:bg-white/5 font-mono font-bold text-xs uppercase tracking-widest flex items-center justify-center gap-2 transition-all cursor-pointer"
                >
                  <span>[ Mark Step Complete ]</span>
                </button>
              </div>
            </div>

            {/* AI Insights Card */}
            <div className="bg-[#111111] border border-white/10 p-6 space-y-4">
              <div className="flex items-center gap-2 text-primary font-mono font-bold text-xs uppercase tracking-widest">
                <Sparkles size={14} />
                <span>AI ASSISTANT DIAGNOSTICS</span>
              </div>
              <ul className="space-y-3 font-sans">
                {plan.insights.slice(1).map((insight, index) => (
                  <li key={index} className="flex items-start gap-3.5 p-3.5 bg-[#050505] border border-white/5 transition-all">
                    <div className="mt-0.5 flex-shrink-0 w-6 h-6 flex items-center justify-center bg-primary/10 text-primary">
                      <Sparkles size={11} />
                    </div>
                    <p className="text-xs text-white/70 leading-relaxed font-light">
                      {insight}
                    </p>
                  </li>
                ))}
              </ul>
            </div>
          </section>

          {/* Roadmap Column */}
          <section className="space-y-6">
            <div className="bg-[#111111] border border-white/10 p-6 flex flex-col h-full">
              <div className="flex justify-between items-center mb-6">
                <h4 className="text-xs font-mono font-bold tracking-widest text-white uppercase">// TARGET ROADMAP</h4>
                <span className="text-[10px] font-mono font-bold text-white/40 uppercase tracking-widest">{plan.milestones.length} STAGES</span>
              </div>

              {/* Add Milestone Form container */}
              {showAddForm ? (
                <form onSubmit={handleAddMilestone} className="p-4 bg-[#050505] border border-white/10 mb-6 space-y-3 font-mono">
                  <input
                    type="text"
                    required
                    value={newTitle}
                    onChange={(e) => setNewTitle(e.target.value)}
                    placeholder="MILESTONE TITLE..."
                    className="w-full bg-[#111111] border border-white/5 text-xs px-3 py-2 text-white outline-none focus:border-primary uppercase tracking-widest"
                  />
                  <input
                    type="text"
                    value={newDesc}
                    onChange={(e) => setNewDesc(e.target.value)}
                    placeholder="SPECIFICATION..."
                    className="w-full bg-[#111111] border border-white/5 text-xs px-3 py-2 text-white outline-none focus:border-primary uppercase tracking-widest"
                  />
                  <div className="flex justify-between items-center pt-2">
                    <select
                      value={newDiff}
                      onChange={(e) => setNewDiff(e.target.value)}
                      className="bg-[#111111] border border-white/5 text-[10px] py-1.5 px-2 text-white outline-none font-bold uppercase tracking-wider"
                    >
                      <option value="Low">Low Difficulty</option>
                      <option value="Medium">Medium Difficulty</option>
                      <option value="High">High Difficulty</option>
                    </select>
                    <div className="flex gap-2">
                      <button
                        type="button"
                        onClick={() => setShowAddForm(false)}
                        className="px-2.5 py-1 text-[10px] text-white/50 hover:text-white uppercase font-bold"
                      >
                        Cancel
                      </button>
                      <button
                        type="submit"
                        className="px-3 py-1 bg-primary text-black text-[10px] font-bold uppercase tracking-widest"
                      >
                        Save
                      </button>
                    </div>
                  </div>
                </form>
              ) : (
                <button
                  onClick={() => setShowAddForm(true)}
                  className="w-full py-4 mb-6 border border-dashed border-white/10 hover:border-primary text-white/40 hover:text-primary transition-all text-xs font-mono font-bold uppercase tracking-widest cursor-pointer bg-transparent"
                >
                  <span>[ ADD ROADMAP LAYER ]</span>
                </button>
              )}

              {/* dashed vertical timeline */}
              <div className="relative pl-6 space-y-6 font-mono">
                {/* Dashed background line */}
                <div className="absolute left-[9px] top-2 bottom-2 w-0.5 border-l border-dashed border-white/10"></div>

                {plan.milestones.map((milestone, idx) => {
                  const isWorking = milestone.status === "WORKING NOW" || idx === activeStep;
                  const isCompleted = milestone.status === "COMPLETED" || idx < activeStep;

                  return (
                    <div
                      key={idx}
                      onClick={() => handleSelectStep(idx)}
                      className={`relative group cursor-pointer transition-opacity duration-200 ${
                        isWorking ? "opacity-100" : isCompleted ? "opacity-80" : "opacity-40 hover:opacity-75"
                      }`}
                    >
                      {/* Circle Status Marker */}
                      <div className={`absolute -left-[23px] top-0.5 w-5 h-5 flex items-center justify-center z-10 transition-all ${
                        isCompleted
                          ? "bg-primary text-black"
                          : isWorking
                          ? "bg-[#CCFF00] text-black"
                          : "bg-[#050505] border border-white/10 text-white/20"
                      }`}>
                        {isCompleted ? (
                          <Check size={10} className="text-black font-black" />
                        ) : (
                          <span className="w-1 h-1 bg-current"></span>
                        )}
                      </div>

                      <div className="min-w-0">
                        <p className={`text-[8px] font-bold tracking-widest uppercase ${
                          isCompleted ? "text-primary" : isWorking ? "text-[#CCFF00]" : "text-white/40"
                        }`}>
                          {milestone.status}
                        </p>
                        <p className={`text-xs font-bold leading-snug mt-1 uppercase tracking-wider ${isWorking ? "text-primary font-display" : "text-white"}`}>
                          {milestone.title}
                        </p>
                        <p className="text-[9px] text-white/40 mt-1 uppercase tracking-widest font-light">
                          {milestone.durationTracked}
                        </p>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </section>
        </div>

        {/* Rescue Trajectory Visual Representation */}
        <section className="bg-[#111111] p-6 md:p-8 border border-white/10 relative overflow-hidden group">
          <div className="z-10 relative flex flex-col md:flex-row items-center gap-6 justify-between">
            <div className="max-w-md space-y-2 text-center md:text-left">
              <span className="inline-flex items-center gap-1.5 text-[9px] font-mono font-bold text-primary bg-primary/5 px-2.5 py-1 border border-primary/20">
                <TrendingUp size={11} />
                <span>VELOCITY PROTOCOL</span>
              </span>
              <h5 className="text-xl font-black font-display text-white italic">Rescue Trajectory</h5>
              <p className="text-xs text-white/50 leading-relaxed font-sans font-light mt-2">
                System estimates cognitive velocity is 20% higher than peak. You are computed to complete goals 45 minutes before critical bounds.
              </p>
            </div>

            {/* SVG custom minimalist line chart represent trajectory visual */}
            <div className="w-full md:w-80 h-32 bg-[#050505] border border-white/10 relative flex items-end justify-center overflow-hidden p-2">
              <svg className="w-full h-full" viewBox="0 0 300 120" preserveAspectRatio="none">
                <defs>
                  <linearGradient id="chartGlow" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor="#CCFF00" stopOpacity="0.3" />
                    <stop offset="100%" stopColor="#CCFF00" stopOpacity="0.0" />
                  </linearGradient>
                </defs>
                {/* Trajectory path area */}
                <path
                  d="M0,110 Q40,95 80,80 T160,50 T240,25 T300,10 L300,120 L0,120 Z"
                  fill="url(#chartGlow)"
                />
                {/* Trajectory path stroke line */}
                <path
                  d="M0,110 Q40,95 80,80 T160,50 T240,25 T300,10"
                  fill="none"
                  stroke="#CCFF00"
                  strokeWidth="2.5"
                />
                {/* Guide grid line */}
                <line x1="0" y1="90" x2="300" y2="90" stroke="#333333" strokeDasharray="3,3" />
                <line x1="0" y1="50" x2="300" y2="50" stroke="#333333" strokeDasharray="3,3" />
              </svg>
              <span className="absolute bottom-2 left-3 text-[9px] font-mono text-white/30 font-semibold uppercase">T-MINUS 3H</span>
              <span className="absolute top-2 right-3 text-[9px] font-mono text-primary font-bold flex items-center gap-1">
                <span>+20% VELOCITY</span>
              </span>
            </div>
          </div>
        </section>
      </div>

      {/* Floating emergency trigger */}
      <div className="fixed bottom-6 right-6 z-40">
        <button
          onClick={() => setShowEmergencyModal(true)}
          className="flex items-center gap-2 bg-red-500 hover:bg-white text-black hover:text-black px-6 h-14 font-mono font-bold text-xs uppercase tracking-widest shadow-2xl active:scale-95 transition-all cursor-pointer"
        >
          <AlertOctagon size={16} className="animate-pulse text-black" />
          <span>[ Emergency Rescue ]</span>
        </button>
      </div>

      {/* Emergency Modal Popup */}
      {showEmergencyModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
          <div className="bg-[#111111] border border-red-500/20 max-w-md w-full p-6 md:p-8 space-y-5 shadow-2xl text-center relative overflow-hidden">
            <div className="absolute top-0 inset-x-0 h-1 bg-red-500"></div>
            <div className="w-14 h-14 bg-red-500/10 text-red-500 flex items-center justify-center mx-auto mb-2 border border-red-500/20">
              <AlertOctagon size={24} className="animate-bounce" />
            </div>
            <h3 className="text-xl font-black font-display italic text-white">Emergency Protocol</h3>
            <p className="text-xs text-white/60 leading-relaxed font-sans font-light">
              Stress index exceeds standard parameters. We recommend triggering a 5-minute tactical box breathing cycle to restore focus capability.
            </p>
            <div className="bg-[#050505] p-4 text-left border border-white/5 space-y-2 font-mono text-xs">
              <p className="font-bold text-primary">PROTOCOL METRICS:</p>
              <ul className="space-y-1.5 text-white/50 text-[11px]">
                <li>• INHALE SLOWLY THROUGH NOSE FOR 4 SECONDS</li>
                <li>• HOLD INTELLECTUAL BREATH FOR 4 SECONDS</li>
                <li>• COMPLETE EXHALATION FOR 4 SECONDS</li>
                <li>• HOLD SYSTEM EMPTY FOR 4 SECONDS</li>
              </ul>
            </div>
            <div className="flex gap-4 pt-2 font-mono">
              <button
                onClick={() => setShowEmergencyModal(false)}
                className="flex-1 py-3 border border-white/10 text-white/60 hover:text-white uppercase font-bold text-xs cursor-pointer transition-all bg-transparent"
              >
                Dismiss Protocol
              </button>
              <button
                onClick={() => {
                  setShowEmergencyModal(false);
                  setIsTimerRunning(false);
                  alert("Focus timer paused. Stand up, stretch, and take a 5 minute break!");
                }}
                className="flex-1 py-3 bg-red-500 text-black hover:bg-white uppercase font-bold text-xs cursor-pointer transition-all border-none"
              >
                Trigger 5M Rest
              </button>
            </div>
          </div>
        </div>
      )}
    </main>
  );
}
